apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

labels:
  - pairs:
      control-plane: catalogd-controller-manager
    includeSelectors: true
    includeTemplates: true

images:
- name: controller
  newName: quay.io/operator-framework/catalogd
  newTag: ${VERSION}
