---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudnative-pg
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudnative-pg-installer
  namespace: cloudnative-pg
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudnative-pg-installer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cloudnative-pg-installer
  namespace: cloudnative-pg
---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: cloudnative-pg
spec:
  namespace: cloudnative-pg
  serviceAccount:
    name: cloudnative-pg-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: cloudnative-pg
      version: 1.24.1
