{
 "title": "Catalogd",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Image Resolutions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(owner_id) (increase(containers_image_resolve_digest_count[$__rate_interval]))",
     "legendFormat": "Resoutions ({{owner_id}})"
    }
   ]
  },
  {
   "title": "Image Pulls",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(owner_id) (increase(containers_image_pull_image_count[$__rate_interval]))",
     "legendFormat": "{{owner_id}}"
    }
   ]
  },
  {
   "title": "Catalogd memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"catalogd-service\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum by(__name__) ({__name__=~\"go_memory_classes_heap.*\", job=\"catalogd-service\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}