apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - coverage_pvc.yaml
  - coverage_copy_pod.yaml
  - registries_conf_configmap.yaml
  - e2e_dummy_cert.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: control-plane=operator-controller-controller-manager
    path: patches/operator_controller_deployment.yaml

  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: control-plane=catalogd-controller-manager
    path: patches/catalogd_deployment.yaml
