apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- network_policy.yaml

labels:
- pairs:
    control-plane: operator-controller-controller-manager
  includeSelectors: true
  includeTemplates: true

images:
- name: controller
  newName: quay.io/operator-framework/operator-controller
  newTag: ${VERSION}
