{{- $installNamespace := .Release.Namespace -}}

{{- $serviceAccountNames := list -}}
{{- range .Values.csv.spec.install.spec.permissions -}}
  {{- if not (has .serviceAccountName $serviceAccountNames) -}}
    {{- $serviceAccountNames = append $serviceAccountNames .serviceAccountName -}}
  {{- end -}}
{{- end -}}
{{- range .Values.csv.spec.install.spec.clusterPermissions -}}
  {{- if not (has .serviceAccountName $serviceAccountNames) -}}
    {{- $serviceAccountNames = append $serviceAccountNames .serviceAccountName -}}
  {{- end -}}
{{- end -}}
{{- if eq (len $serviceAccountNames) 0 -}}
  {{- $serviceAccountNames = list "default" -}}
{{- end -}}
{{- range $serviceAccountNames -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  namespace: {{ $installNamespace }}
{{- end -}}
